version: 1.0.0.{build}
os: Visual Studio 2015
services:
- mongodb
environment:
  COVERALLSKEY:
    secure: v0sCe3/mUj3Tuxri4ajU8igNMpc8CAfknI8SI25o0JwslEedVvCm4KC4QfuO++EW
test: off
build_script:
- cmd: build.cmd ci coverallskey=%COVERALLSKEY%
cache:
- packages -> **\packages.config
